spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8081

app:
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    access-token-expiry-ms: ${JWT_ACCESS_TOKEN_EXPIRY_MS:900000}
    refresh-token-expiry-ms: ${JWT_REFRESH_TOKEN_EXPIRY_MS:2592000000}
  refresh-token:
    expiry-days: 30

redis:
  cache:
    password-reset:
      ttl: 900000
    email-verification:
      ttl: 900000

logging:
  level:
    root: INFO
